CREATE TABLE users (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(510) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    description TEXT,
    gender VARCHAR(62),
    premium DATETIME,
    userType INT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tabela de Aulas
CREATE TABLE classes (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    instructorId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    happensAt DATETIME NOT NULL,
    cost DECIMAL(10, 2) NOT NULL,
    extraFiles TEXT,
    tags TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (instructorId) REFERENCES users(id)
);

CREATE TABLE sells (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    studentId INT NOT NULL,
    classId INT NOT NULL,
    cost DECIMAL(10, 2) NOT NULL,
    soldAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (studentId) REFERENCES users(id),
    FOREIGN KEY (classId) REFERENCES classes(id)
);

CREATE TABLE evaluations (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    classId INT NOT NULL,
    studentId INT NOT NULL,
    note DECIMAL(2, 1) NOT NULL CHECK (note >= 0 AND note <= 10),
    contents TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (classId) REFERENCES classes(id),
    FOREIGN KEY (studentId) REFERENCES users(id)
);

CREATE TABLE messages (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    senderId INT NOT NULL,
    recipientId INT NOT NULL,
    contents TEXT NOT NULL,
    sentAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (senderId) REFERENCES users(id),
    FOREIGN KEY (recipientId) REFERENCES users(id)
);

CREATE TABLE forum_posts (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    authorId INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    contents TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (authorId) REFERENCES users(id)
);
